"use client";

import { useState, useRef } from "react";
import ProjectCard from "./ProjectCard";
import ProjectTag from "./ProjectTag";
import { motion, useInView } from "framer-motion";

const projectsData = [
  {
    id: 1,
    title: "Poke Trades",
    description:
      "A place where users can track their collections and connect to other collectors worldwide to trade. Built on NextJS, React, Drizzle, ShadCN, Tailwind, Resend, NextAuth and Postgres",
    image: "/images/projects/poke-trades.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://poke-trades.com",
  },
  {
    id: 2,
    title: "Restaurant Demo 2",
    description:
      "Using AI and some simple prompts, create video shorts with a few clicks with autogenerated scripts, annotation and narration. Uses Google Gemini for script generation, Firebase for audio/video storage, Google TextToSpeech for audio, Replicate for image generation, AssemblyAI for captions and Remotion for video.",
    image: "/images/projects/ai-short.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://ai-video-shorts-generator.vercel.app",
  },
  {
    id: 3,
    title: "UBet",
    description:
      "Play money Web3 where app where you can bet other people using the Solana network.",
    image: "/images/projects/ubet.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://ubet-ui.vercel.app/",
  },
];

const cardVariants = {
  initial: { y: 52, opacity: 0 },
  animate: { y: 0, opacity: 1 },
};

const Projects = () => {
  const ref = useRef(null);
  const [tag, setTag] = useState("All");
  const isInView = useInView(ref, { once: true });

  const handleTagChange = (name: string) => setTag(name);

  const filteredProjects = projectsData.filter((project) =>
    project.tag.includes(tag)
  );

  return (
    <section ref={ref}>
      <h2 className="text-center text-4xl font-bold text-white mb-8">
        My Projects
      </h2>
      {/* <div className="text-white flex justify-center items-center gap-2 py-6">
        <ProjectTag
          onClick={handleTagChange}
          name="All"
          isSelected={tag === "All"}
        />
        <ProjectTag
          onClick={handleTagChange}
          name="Web"
          isSelected={tag === "Web"}
        />
        <ProjectTag
          onClick={handleTagChange}
          name="Mobile"
          isSelected={tag === "Mobile"}
        />
      </div> */}
      <ul className="grid md:grid-cols-3 gap-8 md:gap-12">
        {filteredProjects.map((project, index) => (
          <motion.li
            variants={cardVariants}
            initial="initial"
            animate={isInView ? "animate" : "initial"}
            key={project.id}
            transition={{ duration: 0.3, delay: index * 0.4 }}
          >
            <ProjectCard
              title={project.title}
              description={project.description}
              imgUrl={project.image}
              gitUrl={project.gitUrl}
              previewUrl={project.previewUrl}
            />
          </motion.li>
        ))}
      </ul>
    </section>
  );
};

export default Projects;
